### ISSUE TITLE
Syntax Error on Windows with Python 2.7

### ISSUE THREAD

**Issue by Michael-Bell** [bell345/gif2xls#1]
```
PS C:\Users\Michael\gif2xls> gif2xls gif.gif -o out.xlsx
Traceback (most recent call last):
  File "C:\Python27\Scripts\gif2xls-script.py", line 9, in <module>
    load_entry_point('gif2xls==0.2.0', 'console_scripts', 'gif2xls')()
  File "c:\python27\lib\site-packages\gif2xls\__init__.py", line 6, in main
    from .__main__ import main
  File "c:\python27\lib\site-packages\gif2xls\__main__.py", line 15
    print(msg, file=sys.stderr)
                   ^
SyntaxError: invalid syntax
```

Powershell on Windows 10, running Python 2.7

**Comment by bell345** [comment]
This is caused by my use of idioms that only exist on Python 3 - I'll fix it in a few hours by using python-future.

**Comment by bell345** [comment]
OK, let me know if that latest commit fixed your issue.

**Comment by Michael-Bell** [comment]
Hmmm, now I'm getting a memory error. Looks like my python installation can only use 2gb of memory. _But_ since my original issue is gone, this can be marked as closed. 

```
PS C:\Users\Michael\gif2xls> gif2xls gif.gif -o out.xlsx
Traceback (most recent call last):
  File "C:\Python27\Scripts\gif2xls-script.py", line 9, in <module>
    load_entry_point('gif2xls==0.2.1', 'console_scripts', 'gif2xls')()
  File "c:\python27\lib\site-packages\gif2xls\__init__.py", line 7, in main
    main(*args, **kwargs)
  File "c:\python27\lib\site-packages\gif2xls\__main__.py", line 59, in main
    content = fancy(gif, format=fmt, cell_width=args.width)
  File "c:\python27\lib\site-packages\gif2xls\fancy.py", line 93, in gif2xls
    return gif2xls_xlsx(gif, cell_width=cell_width)
  File "c:\python27\lib\site-packages\gif2xls\fancy.py", line 39, in gif2xls_xlsx
    xlsx = add_frame_xlsx(xlsx, frame, "Frame {}".format(i), cell_width=cell_width)
  File "c:\python27\lib\site-packages\gif2xls\fancy.py", line 28, in add_frame_xlsx
    sheet.write(j, i, None, fmt)
  File "c:\python27\lib\site-packages\xlsxwriter\worksheet.py", line 64, in cell_wrapper
    return method(self, *args, **kwargs)
  File "c:\python27\lib\site-packages\xlsxwriter\worksheet.py", line 376, in write
    return self.write_blank(row, col, *args)
MemoryError
Exception Exception:  in <bound method Workbook.__del__ of <xlsxwriter.workbook.Workbook object at 0x03762610>> ignored
```

![gif.gif](https://thumbs.gfycat.com/NeglectedThriftyAzurevase-size_restricted.gif)
